### ISSUE TITLE
Bug: Pfp and custom nicknames are not centered. User pop-out sometimes glitches to the left.

### ISSUE THREAD

**Issue by VerMishelb** [moyaiu/OldCord#10]
**Where is it?**
Whenever you click the user pop-out while he has a custom server nickname the nickname is not centered. Also I still think that profile picture is not centered even for the latest version. For me the pixel-perfect center was "left: 31.5%". The image below has 90px before the pfp and 82px after.

**Screenshots**
![image](https://user-images.githubusercontent.com/57833258/150318630-20e79246-1fec-43b6-baff-08d478c96c39.png)
**Additional context**
Sometimes my own pop-out glitches out and moves all stuff to the left until the next opening. The image is quite old but that still happens nearly the same way randomly.
![image](https://user-images.githubusercontent.com/57833258/150319786-92596698-3a46-41f0-9af9-a94d9fb3abae.png)

**Comment by DaSussy** [comment]
> Sometimes my own pop-out glitches out and moves all stuff to the left until the next opening. The image is quite old but that still happens nearly the same way randomly.

i sadly dont know the cause :/
