### ISSUE TITLE
Discord Developers server icon in folders is rebranded

### ISSUE THREAD

**Issue by compwnter** [moyaiu/OldCord#13]
Nitpicking :trollface:
![image](https://user-images.githubusercontent.com/64485899/161378571-804185e3-149b-4bac-a28f-f77a1aa792c6.png)

**Comment by compwnter** [comment]
Links: https://cdn.discordapp.com/icons/613425648685547541/a_6375907799aa6ff2499a1e729a594739.webp?size=20
https://cdn.discordapp.com/icons/613425648685547541/a_6375907799aa6ff2499a1e729a594739.gif?size=20

**Comment by DaSussy** [comment]
cmon 😤

**Comment by compwnter** [comment]
![clash-royale](https://user-images.githubusercontent.com/64485899/161378681-6208dda8-c482-4c11-a969-cb4304b983f3.gif)
