### ISSUE TITLE
BetterDiscord inputs aren't fully rebranded

### ISSUE THREAD

**Issue by compwnter** [moyaiu/OldCord#14]
![image](https://user-images.githubusercontent.com/64485899/161378923-433b4ad3-2d60-4772-b716-641e143f8132.png)
![image](https://user-images.githubusercontent.com/64485899/161378943-8eeaa5d7-8fe1-4651-86d7-b1471876a488.png)
![image](https://user-images.githubusercontent.com/64485899/161378971-458a4ae7-42fd-4f50-a6cd-aec082fe796d.png)
imma just attach a vid of a cat in water and skadoodle outta here
https://user-images.githubusercontent.com/64485899/161379006-58ec6610-d3af-4e4c-9d35-734f022a884a.mp4

**Comment by DaSussy** [comment]
🗿

**Comment by compwnter** [comment]
:trollface:

**Comment by compwnter** [comment]
also may i mention that the transition isn't the same? HEHEHEHA

**Comment by DaSussy** [comment]
> also may i mention that the transition isn't the same? HEHEHEHA

![image](https://user-images.githubusercontent.com/51537072/161379133-5412ff69-0341-4db4-bf1e-f75096bc8c82.png)
![image](https://user-images.githubusercontent.com/51537072/161379134-a2e39d3f-2d55-4bf6-87bc-ebad4fcaadc6.png)
![image](https://user-images.githubusercontent.com/51537072/161379135-3a782adf-f622-4ee6-ba41-9ec48f2b0509.png)
![image](https://user-images.githubusercontent.com/51537072/161379136-7f438af8-130e-4837-8251-299bbe7cb66e.png)
![image](https://user-images.githubusercontent.com/51537072/161379137-dd8e37b9-e2d6-4cbe-98ec-850f6aa0f3f9.png)

**Comment by compwnter** [comment]
moyai is going through a mental breakdown because compwnter keeps nitpicking

**Comment by compwnter** [comment]
xD
