### ISSUE TITLE
Forum Channels skill issues

### ISSUE THREAD

**Issue by Compwnter** [moyaiu/OldCord#20]
🗿
![image](https://user-images.githubusercontent.com/64485899/187034098-36763d2f-7759-4312-9ef1-c25fd9757729.png)
![image](https://user-images.githubusercontent.com/64485899/187034100-02cee64c-324c-4e1e-9c51-01e48697c700.png)

**Comment by DaSussy** [comment]
i dont even have access to forum channels 😤
