### ISSUE TITLE
About Me + Note skill issue

### ISSUE THREAD

**Issue by Compwnter** [moyaiu/OldCord#22]
idk what to call it so ill just call it a skill issue, see for urself ig lmao
![image](https://user-images.githubusercontent.com/64485899/187095500-464e694c-bee2-42d1-b47c-a01d2d10dce0.png)

**Comment by toydotgame** [comment]
GitHub Issues tab should be renamed to Skill Issues tab, huh?

**Comment by toydotgame** [comment]
```js
document.getElementById("issues-tab").getElementsByTagName("span")[0].innerHTML = document.getElementById("issues-tab").getElementsByTagName("span")[0].innerHTML.replace("Issues", "Skill Issues");
```

**Comment by DaSussy** [comment]
i have a life + ratio

**Comment by DaSussy** [comment]
![image](https://user-images.githubusercontent.com/51537072/187409171-3bf7cf1d-4c7f-4488-aa1b-10dce608022d.png)
bruh 💀

**Comment by DaSussy** [comment]
unless u send me the classes or make a pr, i cant fix that
