### ISSUE TITLE
Weird profile panel

### ISSUE THREAD

**Issue by jozsaVilmos** [moyaiu/OldCord#24]
If I turn off the theme it's the same.

https://i.gyazo.com/8b6f04d896b691ae6d1ff82cc0dbebca.png

**Comment by Compwnter** [comment]
thank discord for making more of their useless updates that nobody asks for

**Comment by DaMoyai** [comment]
thank discord for making 1million stupid changes in their css everyday, wont fix for atlaest another week because this isnt worth it

**Comment by Compwnter** [comment]
> thank discord for making 1million stupid changes in their css everyday, wont fix for atlaest another week because this isnt worth it

ARE YOU SERIOUS RIGHT NEOW BRO

**Comment by DaMoyai** [comment]
> > thank discord for making 1million stupid changes in their css everyday, wont fix for atlaest another week because this isnt worth it
> 
> ARE YOU SERIOUS RIGHT NEOW BRO

no
