### ISSUE TITLE
how did u even manage to break this again

### ISSUE THREAD

**Issue by Compwnter** [moyaiu/OldCord#25]
![image](https://user-images.githubusercontent.com/64485899/192337140-4ae7bc79-4a61-447c-80b7-57fd038aed63.png)

**Comment by Compwnter** [comment]
https://user-images.githubusercontent.com/64485899/192337183-449a01ae-2f48-4122-8729-cb44171ae0f5.mp4

**Comment by DaMoyai** [comment]
ask discord

**Comment by Compwnter** [comment]
ask some bitches out

**Comment by DaMoyai** [comment]
🗿
![image](https://user-images.githubusercontent.com/51537072/192652756-826577d0-19f4-401b-a938-7d5ddd8df1c7.jpeg)
