### ISSUE TITLE
not really issue just a querie

### ISSUE THREAD

**Issue by thehomelander11** [moyaiu/OldCord#29]
will the old profile looks be able to come back?

**Comment by DaMoyai** [comment]
![image](https://user-images.githubusercontent.com/51537072/193401138-eec844ae-5302-41a5-9895-d242253ba570.png)
if you mean this new ui, ill try to edit it later, but the role color thing could be difficult

**Comment by thehomelander11** [comment]
![add-friend-discord-8.png](https://user-images.githubusercontent.com/114253537/193404737-523909c1-3421-4b55-8c6a-8079e7e28ed5.png)

Yeah I just mean trying to get them to look like this, otherwise thanks for the reply 👍

**Comment by toydotgame** [comment]
+1'ing this issue alongside the old profiles (i miss them maybe the most out of all of the changes i think)
![image](https://user-images.githubusercontent.com/64190512/193446103-bec5b634-fb01-4e06-9402-8bd88f457477.png)
![image](https://user-images.githubusercontent.com/64190512/193446154-ca7c9721-48fc-4fdc-851f-93eae3bb160e.png)
(old screenshots from mid 2020 but censored the second one to not expose my irl friends names)
(also dont mention my picrew pfp i know i was cringe🐺) lmao

**Comment by DaMoyai** [comment]
> +1'ing this issue alongside the old profiles (i miss them maybe the most out of all of the changes i think) ![image](https://user-images.githubusercontent.com/64190512/193446103-bec5b634-fb01-4e06-9402-8bd88f457477.png) ![image](https://user-images.githubusercontent.com/64190512/193446154-ca7c9721-48fc-4fdc-851f-93eae3bb160e.png) (old screenshots from mid 2020 but censored the second one to not expose my irl friends names) (also dont mention my picrew pfp i know i was cringewolf) lmao

banned for picrew pfp°!!!!1

that blurple background isnt possible anymore 😔
and reverting that shitty ui takes so much time omfg

**Comment by thehomelander11** [comment]
![image](https://user-images.githubusercontent.com/114253537/193455253-c517c40e-6d69-4a34-8c40-133a87be27af.png)
I added a css to remove member since, but that still shows *MEMBER SINCE* but does remove the icons and join date, the only problem is removing the about me and custom statuses which don't have the right background colour and finally the playing a game part margin is too far to the left. I dont know how this helps lol but I thought Id put it here

**Comment by toydotgame** [comment]
> that blurple background isnt possible anymore :pensive:
 really? why not? isn't it just some background colour for the profile modal? seems kinda simple but i wouldnt be surprised if discord made it have the world's most overcomplicated and non functional css

**Comment by DaMoyai** [comment]
> > that blurple background isnt possible anymore pensive
> 
> really? why not? isn't it just some background colour for the profile modal? seems kinda simple but i wouldnt be surprised if discord made it have the world's most overcomplicated and non functional css

it was another css class, but discord removed it

**Comment by DaMoyai** [comment]
fixed now but who knows for how long 🫠
