### ISSUE TITLE
Bug: Incorrect padding

### ISSUE THREAD

**Issue by petrolizing** [moyaiu/OldCord#3]
**Where is it?**
The padding encircling the user's profile picture when a profile has a status, there's like 6 cubic pixels that are left with a different light gray color than the normal dark gray color; only people with statuses have this bug and it's just the padding position or amount lower by a few digits on the last line segment; if there's an about me on someone's profile or a status the function that makes the default padding for the space around the profile picture is the amount of padding a user with no status nor about me description which is low because profile guis get taller the more text there is, it should be till to this line
![image](https://user-images.githubusercontent.com/72923451/135117954-9e8829eb-7c39-4272-afe9-8514bae2281f.png) or whatever the old padding was till, and the cubic pixels that are left out being light gray and not apart of the padding which I mentioned earlier can just be filled with the increase of the padding amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/72923451/135112730-a1fa2d23-4244-4588-ad70-c565dd72549d.png)

**Additional context**
N/A

**Comment by DaSussy** [comment]
lmao aight fixing later 🗿

**Comment by DaSussy** [comment]
![image](https://user-images.githubusercontent.com/51537072/135148192-9cb5260d-0f0a-4d4e-b66c-6feaa827b816.png)
this is part of the scrollbar thing. idk if i can do something about this but im trying rn

**Comment by petrolizing** [comment]
thank you so much for even responding, I thought I was gonna be ignored

**Comment by petrolizing** [comment]
its fine, hopefully you can change make the scrollbar invisible and add the padding color to it

**Comment by DaSussy** [comment]
> its fine, hopefully you can change make the scrollbar invisible and add the padding color to it

couldnt find a way to fix it :/

**Comment by petrolizing** [comment]
its fine

**Comment by DaSussy** [comment]
ok i did find a way, will commit it later cuz im doing some other changes too

**Comment by petrolizing** [comment]
thank you so much, you were just probably on a rush

**Comment by petrolizing** [comment]
it didn't work, this is what the ui looks like now 
![image](https://user-images.githubusercontent.com/72923451/135336194-f98a75d3-864f-490a-9c63-9314314763da.png)

**Comment by DaSussy** [comment]
try it now

**Comment by petrolizing** [comment]
it worked but you forgot what I said in the main message about the line interposing profile picture and the about me or note description, this 
![image](https://user-images.githubusercontent.com/72923451/135391868-6199b7c4-f2b6-4f5a-9452-ac778d7d09d9.png)
whatever class/line of code you repasted for the profile picture's padding was equivalent to the amount of padding a profile with no status has. just make a class for profiles with statuses and no statuses and import it, and this is the line im talking about 
![image](https://user-images.githubusercontent.com/72923451/135392296-fbea47af-de1c-4ef6-9ce8-46b3f031f6f8.png)

**Comment by DaSussy** [comment]
thats weird, i dont see the line at all

**Comment by petrolizing** [comment]
what how so

**Comment by petrolizing** [comment]
the padding is too small for people with statuses you can just fill it like the old padding without needing to see the line but the line is there maybe its just too small and not really clear to you

**Comment by DaSussy** [comment]
ok i found the issues, and im fixing them now

**Comment by petrolizing** [comment]
thank you so much

**Comment by petrolizing** [comment]
yes it worked. one more thing if you're free, could you add a disable/enable banners button I just got reminded from the old closed issues.

**Comment by petrolizing** [comment]
and will commit files merge with the main old cord directory so that you could paste only one import url instead of pasting both of them

**Comment by petrolizing** [comment]
last bug I just found is the spotify favicon and button guis being aligned to the right instead of the middle, same thing that happened to status text is happening to the gui because you forgot to align them too 
![image](https://user-images.githubusercontent.com/72923451/135421991-4c49ce4a-c218-4ef1-9437-18296e43af5c.png)

**Comment by DaSussy** [comment]
> last bug I just found is the spotify favicon and button guis being aligned to the right instead of the middle, same thing that happened to status text is happening to the gui because you forgot to align them too 
> 
> ![image](https://user-images.githubusercontent.com/72923451/135421991-4c49ce4a-c218-4ef1-9437-18296e43af5c.png)
> 
> 

oh yeah my bad, lemme fix

**Comment by petrolizing** [comment]
thank you

**Comment by petrolizing** [comment]
> > last bug I just found is the spotify favicon and button guis being aligned to the right instead of the middle, same thing that happened to status text is happening to the gui because you forgot to align them too
> > ![image](https://user-images.githubusercontent.com/72923451/135421991-4c49ce4a-c218-4ef1-9437-18296e43af5c.png)
> 
> oh yeah my bad, lemme fix

sorry for annoying you, but where's the commit

**Comment by DaSussy** [comment]
> > > last bug I just found is the spotify favicon and button guis being aligned to the right instead of the middle, same thing that happened to status text is happening to the gui because you forgot to align them too
> 
> > > ![image](https://user-images.githubusercontent.com/72923451/135421991-4c49ce4a-c218-4ef1-9437-18296e43af5c.png)
> 
> > 
> 
> > oh yeah my bad, lemme fix
> 
> 
> 
> sorry for annoying you, but where's the commit

i already know it, its just i dont find a spotify activity to get the class lol

**Comment by petrolizing** [comment]
totally fine, take your time

**Comment by petrolizing** [comment]
worked, thank you so much

**Comment by petrolizing** [comment]
thank you so much for responding, one more thing is the custom status font it looks bold

**Comment by petrolizing** [comment]
no I don't think so it looks so oversaturated doesn't look like the old discord at all

**Comment by DaSussy** [comment]
> ![image](https://user-images.githubusercontent.com/51537072/136232864-9eb5e6b1-8516-4c7c-8b72-aa004249b879.png)
> this is how it used to look like. you're right, its too bold

though in the november 2020 css, the font color is #fff

**Comment by petrolizing** [comment]
@DaSussy , apologies for the tag but this just blurs my eyes.

> then how do I disable the discord support input

**Comment by DaSussy** [comment]
> > then how do I disable the discord support input
> 
> 
> 
> 

wdym 🗿

**Comment by DaSussy** [comment]
yeah, because it was an early screenshot from discord support, but at
around november 2020 the custom status text got bolder and whiter

**Comment by petrolizing** [comment]
how so, the custom status font after the rebrand looks like this: 
![image](https://user-images.githubusercontent.com/72923451/136662227-97d20618-ca65-4fc2-8b7f-ae8579804653.png)
 the old normal font, and I don't recall the custom status font being this white and if it eve

**Comment by DaSussy** [comment]
> how so, the custom status font after the rebrand looks like this: 
> 
> ![image](https://user-images.githubusercontent.com/72923451/136662227-97d20618-ca65-4fc2-8b7f-ae8579804653.png)
> 
>  the old normal font, and I don't recall the custom status font being this white; and if it even was this white could you revert it back to the not bold custom status font

tbh, same. lemme revert to the old color 🗿🗿🗿

**Comment by DaSussy** [comment]
obviously a commit lol

**Comment by DaSussy** [comment]
what do you mean? nothing except the font changed

**Comment by DaSussy** [comment]
![image](https://user-images.githubusercontent.com/51537072/136693752-736b7f90-073f-4e1e-b8f3-b642341725a3.png)

**Comment by petrolizing** [comment]
isn't there a variable or class for game activity mutations or something

**Comment by DaSussy** [comment]
no, not anymore

**Comment by petrolizing** [comment]
okay, thank you so much

**Comment by DaSussy** [comment]
> correct 

tf is this??? anyways, i tried to say yes

**Comment by petrolizing** [comment]
one more thing, if discord plugins are on betterdiscord then you could use javascript to modify the discord api because discord plugins use javascript; you could make a betterdiscord plugin and type in the classes for the game activity ui and just add variables or constants and change their color when an activity is running

**Comment by petrolizing** [comment]
yeah but like you did a miner change to the custom status font but it was a logical change, its just that it looks so weird and I can't fit this in to my head that it was this small

**Comment by DaSussy** [comment]
at first it was weird for me too, but after a few days it wasnt weird at all

**Comment by petrolizing** [comment]
apologies for disturbing you and insisting on a small change and regardless all I can do is change one class and it'll be back (and the banner class and/or any margint transpositions) and instead of gradually mutating my self to the normal one the old one seems to be good, thank you so much for responding so fast

**Comment by DaSussy** [comment]
> apologies for disturbing you and insisting on a small change and regardless all I can do is change one class and it'll be back (and the banner class and/or any margint transpositions) and instead of gradually mutating my self to the normal one the old one seems to be good, thank you so much for responding so fast

yeah np :) everyone can be a bitch sometimes, even me lol

**Comment by petrolizing** [comment]
apologies for overflooding you with bugs, but discord just added a new transition type when you try changing your status instead of it being linear its as if its a fade; could you just find the transition class and change its properties to the old one

**Comment by DaSussy** [comment]
> apologies for overflooding you with bugs, but discord just added a new transition type when you try changing your status instead of it being linear its as if its a fade; could you just find the transition class and change its properties to the old one

oh cmon, thanks for telling me this, imma change it back. good thing that im working on an update rn lol

**Comment by petrolizing** [comment]
thank you so much

**Comment by petrolizing** [comment]
are you gonna make a commit or are you gonna import it to the main folder

**Comment by DaSussy** [comment]
i need to find the animation things but im gonna commit to other.css
obviously

**Comment by petrolizing** [comment]
okay, thank you so much

**Comment by petrolizing** [comment]
if you're trying to find the classes that change the animation type then these are the four classes that change the animation type and padding of the whole status ui's two dimensional perimeter: 
![image](https://user-images.githubusercontent.com/72923451/139806819-7e8ee23d-ef6a-45dc-9ddf-9e2eb96c0b3f.png)

**Comment by petrolizing** [comment]
> if you're trying to find the classes that change the animation type then these are the four classes that change the animation type and padding of the whole status ui's two dimensional perimeter: ![image](https://user-images.githubusercontent.com/72923451/139806819-7e8ee23d-ef6a-45dc-9ddf-9e2eb96c0b3f.png)

@DaSussy

**Comment by petrolizing** [comment]
> > if you're trying to find the classes that change the animation type then these are the four classes that change the animation type and padding of the whole status ui's two dimensional perimeter: ![image](https://user-images.githubusercontent.com/72923451/139806819-7e8ee23d-ef6a-45dc-9ddf-9e2eb96c0b3f.png)
> 
> @DaSussy

@DaSussy

**Comment by DaSussy** [comment]
no matter what i try it stays the same

**Comment by petrolizing** [comment]
hm
