### ISSUE TITLE
Theme Causes Conflictions with Status Menu CSS

### ISSUE THREAD

**Issue by KingGamingYT** [moyaiu/OldCord#31]
I know you probably don't cater to hyper-specific problems like this, but using OldCord in conjunction with a CSS snippet in the BetterDiscord server (shown below) will cause a giant gap to form between the main menu and sub-menus, likely as some sort of class or config confliction. This makes sub-menus nearly un-interactable.
![image](https://user-images.githubusercontent.com/45918062/203898343-b47772b5-4512-421c-af23-749c78619335.png)

CSS:
```
.accountProfilePopoutWrapper-3GskID {
    left: unset;
}

.accountProfilePopoutWrapper-3GskID .userPopoutOuter-3AVBmJ {
    width: 220px;
}

.accountProfilePopoutWrapper-3GskID .userPopoutOverlayBackground-dKOOda {
    margin:0;
    background: none;
}

.accountProfilePopoutWrapper-3GskID .userPopoutInner-1hXSeY > :not(.overlayBackground-1KgwVi),
.accountProfilePopoutWrapper-3GskID .overlayBackground-1KgwVi > :not(#account),
.accountProfilePopoutWrapper-3GskID #account>div>div>#account-divider-1 {
    display:none;
}
```

**Comment by DaMoyai** [comment]
im gonna kms
will fix asap

**Comment by DaMoyai** [comment]
i sort of fixed it?
![image](https://user-images.githubusercontent.com/51537072/204008651-c6a875aa-2bb8-4488-9f02-c2d80e245a25.png)
![image](https://user-images.githubusercontent.com/51537072/204008721-c694eaa2-590f-4814-94e9-20240ce5ce4b.png)
###### wont push this out tho
