### ISSUE TITLE
Another unwanted feature added by Discord.

### ISSUE THREAD

**Issue by jozsaVilmos** [moyaiu/OldCord#33]
I'm not sure if this is even fixable if not please close. Search buttons have been moved up.

https://i.postimg.cc/5ypJKzBx/80aabef1af7f4a35d3c3af6b097c7f1b.png

**Comment by DaMoyai** [comment]
huh? not the case for me... if i get that ill try fixing that, but i assume its unfixable unfortunately

**Comment by DaMoyai** [comment]
> also me the search button thing has also been moved up

bruh what do u mean?

**Comment by DaMoyai** [comment]
hm
