### ISSUE TITLE
Aw heck naw another goofy ahh bug

### ISSUE THREAD

**Issue by foursplaysroblox** [moyaiu/OldCord#38]
![image](https://user-images.githubusercontent.com/82078139/210171708-76c0eb2a-71c6-4bcc-b28c-8696ec9245bc.png)
![image](https://user-images.githubusercontent.com/82078139/210171728-ba2e0e81-2289-4d1b-a95b-bcfdc279def5.png)
![image](https://user-images.githubusercontent.com/82078139/210172108-b9202024-214c-4c97-ab56-80f4c0c9b9e7.png)

**Comment by DaMoyai** [comment]
first one happens for certain people (and im too lazy to fix) but the other 2 never happened for me

**Comment by DaMoyai** [comment]
the first one only happens in the preview, so idgaf but ill fix the other 2

**Comment by foursplaysroblox** [comment]
![QuandaleDingleGIF](https://user-images.githubusercontent.com/82078139/210189426-e9081b0c-4d73-44e0-bea9-be9e6880d65b.gif)

**Comment by foursplaysroblox** [comment]
try also having support for the normal status css in betterdiscord server's #css-snippets because it is broken
![image](https://user-images.githubusercontent.com/82078139/210191279-8a09de58-ec61-4210-b493-a0a615309765.png)

**Comment by DaMoyai** [comment]
how the fuck did this break

**Comment by DaMoyai** [comment]
`
.accountProfilePopoutWrapper-3GskID .bannerSVGWrapper-qc0szY,
.accountProfilePopoutWrapper-3GskID .avatarWrapper-3y0KZ1,
.accountProfilePopoutWrapper-3GskID .profileBadges-31rDHI,
.accountProfilePopoutWrapper-3GskID .userProfileInner-3F03PX:before,
.accountProfilePopoutWrapper-3GskID .userPopoutOverlayBackground-dKOOda div:not(.menu-1QACrS, .menu-1QACrS *),
.accountProfilePopoutWrapper-3GskID [id="account-divider-1"] {
….accountProfilePopoutWrapper-3GskID .menu-KSaHL1 .submenu-1apzyU {
    border-radius: 4px;
    width: 240px;
}
`

the css conflicts with oldcord and makes the width too small, so u gotta use this

**Comment by foursplaysroblox** [comment]
Okay

**Comment by DaMoyai** [comment]
![image](https://user-images.githubusercontent.com/51537072/210529511-6b81c6f1-8fcf-4a4b-92f0-b85040bbc369.png)
now it affected me too 🫠

**Comment by foursplaysroblox** [comment]
Whats up guys it's quandile dingle here Whats up guys it's quandile dingle here Whats up guys it's quandile dingle here
