### ISSUE TITLE
DM activity colour

### ISSUE THREAD

**Issue by Portal2Ben** [moyaiu/OldCord#4]
![image](https://user-images.githubusercontent.com/54502521/139968120-ab09f3ff-14ec-413a-960c-30deaa42134f.png)
^ New discord green colour
![image](https://user-images.githubusercontent.com/54502521/139968151-3851361f-a0da-4f0a-ab91-939a4471bb9f.png)
^ old (better) discord screen colour

![image](https://user-images.githubusercontent.com/54502521/139968285-962837fc-bd44-4794-a289-b1c854aa1bad.png)
Located in the DMs when someone is online

**Comment by Portal2Ben** [comment]
also great theme man! fixes most of the issues with the other one!
also an issue with the folder being the wrong colour till you open it:

![image](https://user-images.githubusercontent.com/54502521/139968431-d3f88c17-2288-461c-b3d8-6ddd1a651361.png)
^ New burple
![image](https://user-images.githubusercontent.com/54502521/139968456-840a112f-b365-4242-9450-05bfec9f9d93.png)
^Old (better) burple

**Comment by DaSussy** [comment]
> also great theme man! fixes most of the issues with the other one! also an issue with the folder being the wrong colour till you open it:
> 
> ![image](https://user-images.githubusercontent.com/54502521/139968431-d3f88c17-2288-461c-b3d8-6ddd1a651361.png) ^ New burple ![image](https://user-images.githubusercontent.com/54502521/139968456-840a112f-b365-4242-9450-05bfec9f9d93.png) ^Old (better) burple

looks like dc changed the class for some reason, lemme fix

**Comment by DaSussy** [comment]
> ![image](https://user-images.githubusercontent.com/54502521/139968120-ab09f3ff-14ec-413a-960c-30deaa42134f.png) ^ New discord green colour ![image](https://user-images.githubusercontent.com/54502521/139968151-3851361f-a0da-4f0a-ab91-939a4471bb9f.png) ^ old (better) discord screen colour
> 
> ![image](https://user-images.githubusercontent.com/54502521/139968285-962837fc-bd44-4794-a289-b1c854aa1bad.png) Located in the DMs when someone is online

its the old color for me
![image](https://user-images.githubusercontent.com/51537072/140033822-49242608-dff6-4254-80c7-24a1c0d73970.png)
