### ISSUE TITLE
you done messed up

### ISSUE THREAD

**Issue by foursplaysroblox** [moyaiu/OldCord#41]
The word Discord is using the new font and it looks trash
![image](https://user-images.githubusercontent.com/82078139/211125656-da69fa98-8e9b-453e-9c29-13d1522a0fc9.png)

**Comment by DaMoyai** [comment]
i dont use windows so can you tell me the class?

**Comment by foursplaysroblox** [comment]
idk what is a class

**Comment by DaMoyai** [comment]
> idk what is a class

💀

**Comment by foursplaysroblox** [comment]
🗿
