### ISSUE TITLE
Suggestion: Use the classic Discord 2016 status icons 🗿

### ISSUE THREAD

**Issue by foursplaysroblox** [moyaiu/OldCord#46]
Hello pls use the discord 2016 status icons for online, dnd, idle, and offline (which is just a circle) and also add the og connections icons and the blue thing when you are playing a game. and also add the old loading screen

![image](https://user-images.githubusercontent.com/82078139/215443078-b74e48ac-356e-434a-957a-d17a6e384085.png)
![image](https://user-images.githubusercontent.com/82078139/215443426-0dbda4ff-5875-4055-86b8-9a1025ae27ea.png)
from the interwebs i mean internet the images

**Comment by foursplaysroblox** [comment]
also use the old hype squand icons too

**Comment by DaMoyai** [comment]
there's a reason why the icons exist, its accessibility. if you really want them back though, there's a plugin called colorsighted

what do you mean with the loading? if you mean the icon, i cant do anything about it, and its honestly not worth it

new hypesquad icons existed in 2020 so..
but here's something you can put in custom css (below the imports)
https://gist.githubusercontent.com/Overimagine1/3c6d074d18047d5aef8f56bd871ae5d7/raw/f1da1c7977a285c4610472c80a9bcfe034aaa185/OldHypesquadIcons.css

**Comment by foursplaysroblox** [comment]
what about the old connection icons
