### ISSUE TITLE
69420th bug report

### ISSUE THREAD

**Issue by foursplaysroblox** [moyaiu/OldCord#47]
![image](https://user-images.githubusercontent.com/82078139/217458156-8dd9e286-d934-4632-b4d4-5b62c4fe2657.png)
![image](https://user-images.githubusercontent.com/82078139/217458230-6b90812f-a7f2-4c8d-a485-9f7faf420d7a.png)
pls fix

**Comment by foursplaysroblox** [comment]
🗿

**Comment by DaMoyai** [comment]
later
