### ISSUE TITLE
Messagebox background stopped existing

### ISSUE THREAD

**Issue by KingGamingYT** [moyaiu/OldCord#48]
![image](https://user-images.githubusercontent.com/45918062/219483476-cbcea1de-31d6-4374-b72e-72844929211e.png)
See above

**Comment by DaMoyai** [comment]
what how

**Comment by KingGamingYT** [comment]
> what how

I have no idea all I know is that when I turn off the theme, it reappears. Also, this only started happening this morning and my custom CSS isn't causing it as removing it all doesn't change anything.

**Comment by DaMoyai** [comment]
they made the colors darker, and made the messagebox use the previous chat color

**Comment by KingGamingYT** [comment]
Well that explains why it almost looked like I could see a ghost box if I squinted. Thanks

**Comment by DaMoyai** [comment]
no problem :)
