### ISSUE TITLE
Profile picture is not centered

### ISSUE THREAD

**Issue by Apeiros-46B** [moyaiu/OldCord#6]
**Where is it?**
If you open someone's profile card, their profile picture is not centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/61390942/141866137-d8bac886-8720-4489-a6e5-bcefb16e20e9.png)

**Additional context**
Zooming in and out with control/command +/- does not appear to affect it.

**Comment by DaSussy** [comment]
im fixing it tomorrow :)

**Comment by DaSussy** [comment]
fixed
